//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Productie
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProdus
    {
        public string numeProdus { get; set; }
        public Nullable<int> lotFabricatie { get; set; }
        public Nullable<System.DateTime> fisaConsum { get; set; }
    }
}
