//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _13_BD_Parc_Auto
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCamioane
    {
        public int Id { get; set; }
        public string Marca { get; set; }
        public Nullable<int> Capacitate { get; set; }
        public Nullable<int> ToneKm { get; set; }
    }
}
